-- Icon group Baby
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/D9v3dcB.png', 'Baby'),
       ('https://i.imgur.com/0lB9I5B.png', 'Baby'),
       ('https://i.imgur.com/3MYn6uw.png', 'Baby'),
       ('https://i.imgur.com/wZ3VG2i.png', 'Baby'),
       ('https://i.imgur.com/Ppk6vlD.png', 'Baby'),
       ('https://i.imgur.com/naM2sss.png', 'Baby'),
       ('https://i.imgur.com/emzByLw.png', 'Baby'),
       ('https://i.imgur.com/T4MlCW5.png', 'Baby'),
       ('https://i.imgur.com/nessiTN.png', 'Baby'),
       ('https://i.imgur.com/5MGFnl0.png', 'Baby'),
       ('https://i.imgur.com/PgwO9ry.png', 'Baby'),
       ('https://i.imgur.com/3UCkMYj.png', 'Baby'),
       ('https://i.imgur.com/onBZS0p.png', 'Baby'),
       ('https://i.imgur.com/vhLitmR.png', 'Baby'),
       ('https://i.imgur.com/L1ztAeY.png', 'Baby'),
       ('https://i.imgur.com/gfxKO5O.png', 'Baby'),
       ('https://i.imgur.com/uKvGlTd.png', 'Baby'),
       ('https://i.imgur.com/JTrqWcE.png', 'Baby'),
       ('https://i.imgur.com/kO4q3Fz.png', 'Baby'),
       ('https://i.imgur.com/MsIm6u5.png', 'Baby');

-- Icon group Couple
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/1ZLzcCM.png', 'Couple'),
       ('https://i.imgur.com/skr3jjY.png', 'Couple'),
       ('https://i.imgur.com/n5TD7n7.png', 'Couple'),
       ('https://i.imgur.com/q4CLMAb.png', 'Couple'),
       ('https://i.imgur.com/3nf8Pcs.png', 'Couple'),
       ('https://i.imgur.com/eMqYrlx.png', 'Couple'),
       ('https://i.imgur.com/SH0bCcc.png', 'Couple'),
       ('https://i.imgur.com/oucckDH.png', 'Couple'),
       ('https://i.imgur.com/7LhY7s7.png', 'Couple'),
       ('https://i.imgur.com/mUg9i9n.png', 'Couple'),
       ('https://i.imgur.com/OteArk2.png', 'Couple'),
       ('https://i.imgur.com/hvPdTNA.png', 'Couple'),
       ('https://i.imgur.com/oYV0LTf.png', 'Couple'),
       ('https://i.imgur.com/k4mJIGA.png', 'Couple');

-- Icon group Giáo dục
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/9SKUv5O.png', 'Giáo dục'),
       ('https://i.imgur.com/UnMFSkB.png', 'Giáo dục'),
       ('https://i.imgur.com/Xk18xuE.png', 'Giáo dục'),
       ('https://i.imgur.com/Hf9rUk8.png', 'Giáo dục'),
       ('https://i.imgur.com/z9MmZLt.png', 'Giáo dục'),
       ('https://i.imgur.com/AYe108Q.png', 'Giáo dục'),
       ('https://i.imgur.com/By8atz1.png', 'Giáo dục'),
       ('https://i.imgur.com/ImcM7Po.png', 'Giáo dục'),
       ('https://i.imgur.com/wCVPQ4P.png', 'Giáo dục'),
       ('https://i.imgur.com/MNLPjU0.png', 'Giáo dục'),
       ('https://i.imgur.com/pwaCYGn.png', 'Giáo dục'),
       ('https://i.imgur.com/c669tSh.png', 'Giáo dục'),
       ('https://i.imgur.com/Euy7udf.png', 'Giáo dục'),
       ('https://i.imgur.com/MqcHZcS.png', 'Giáo dục'),
       ('https://i.imgur.com/5OeltyK.png', 'Giáo dục'),
       ('https://i.imgur.com/X9L3CoE.png', 'Giáo dục'),
       ('https://i.imgur.com/AoS610F.png', 'Giáo dục'),
       ('https://i.imgur.com/VcRm91A.png', 'Giáo dục'),
       ('https://i.imgur.com/dcurooi.png', 'Giáo dục'),
       ('https://i.imgur.com/DyJdup9.png', 'Giáo dục');

-- Icon group Fashion
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/pfrVd9P.png', 'Fashion'),
       ('https://i.imgur.com/E8CfYX9.png', 'Fashion'),
       ('https://i.imgur.com/1kmztRj.png', 'Fashion'),
       ('https://i.imgur.com/IWtrXXf.png', 'Fashion'),
       ('https://i.imgur.com/BgFJdbn.png', 'Fashion'),
       ('https://i.imgur.com/3HimrOc.png', 'Fashion'),
       ('https://i.imgur.com/jGILFbJ.png', 'Fashion'),
       ('https://i.imgur.com/YIqPe0s.png', 'Fashion'),
       ('https://i.imgur.com/dG4twkb.png', 'Fashion'),
       ('https://i.imgur.com/RFJhuhc.png', 'Fashion'),
       ('https://i.imgur.com/0E4TnXY.png', 'Fashion'),
       ('https://i.imgur.com/DpDgLNJ.png', 'Fashion'),
       ('https://i.imgur.com/dEloZNR.png', 'Fashion'),
       ('https://i.imgur.com/D6JfqLv.png', 'Fashion'),
       ('https://i.imgur.com/OyT7j2n.png', 'Fashion'),
       ('https://i.imgur.com/K6SrzaF.png', 'Fashion'),
       ('https://i.imgur.com/xRSaS9Z.png', 'Fashion'),
       ('https://i.imgur.com/xii6Zui.png', 'Fashion'),
       ('https://i.imgur.com/h6KNjfL.png', 'Fashion'),
       ('https://i.imgur.com/eNprlOt.png', 'Fashion'),
       ('https://i.imgur.com/A2H7rIr.png', 'Fashion'),
       ('https://i.imgur.com/jxJI38L.png', 'Fashion'),
       ('https://i.imgur.com/Yz0ckfO.png', 'Fashion'),
       ('https://i.imgur.com/fVpCJz9.png', 'Fashion'),
       ('https://i.imgur.com/W17PFM1.png', 'Fashion'),
       ('https://i.imgur.com/DV5zgI3.png', 'Fashion'),
       ('https://i.imgur.com/soGcbjS.png', 'Fashion'),
       ('https://i.imgur.com/73lY3x9.png', 'Fashion'),
       ('https://i.imgur.com/Kzupiuk.png', 'Fashion'),
       ('https://i.imgur.com/hhs0riD.png', 'Fashion');

-- Icon group Fast Food
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/mrll58B.png', 'Fast Food'),
       ('https://i.imgur.com/EuRq6YO.png', 'Fast Food'),
       ('https://i.imgur.com/BU0XFjv.png', 'Fast Food'),
       ('https://i.imgur.com/EZhSOsW.png', 'Fast Food'),
       ('https://i.imgur.com/tt9zcRm.png', 'Fast Food'),
       ('https://i.imgur.com/0mGwJde.png', 'Fast Food'),
       ('https://i.imgur.com/SiuSgmG.png', 'Fast Food'),
       ('https://i.imgur.com/TduB2di.png', 'Fast Food'),
       ('https://i.imgur.com/aiOZbL1.png', 'Fast Food'),
       ('https://i.imgur.com/E16jOu8.png', 'Fast Food'),
       ('https://i.imgur.com/Mcn12HF.png', 'Fast Food'),
       ('https://i.imgur.com/hRcGsDb.png', 'Fast Food'),
       ('https://i.imgur.com/pZ7KNLo.png', 'Fast Food'),
       ('https://i.imgur.com/HLXSfcI.png', 'Fast Food'),
       ('https://i.imgur.com/n0oR4cq.png', 'Fast Food'),
       ('https://i.imgur.com/IVreyzl.png', 'Fast Food'),
       ('https://i.imgur.com/aXoAcPT.png', 'Fast Food'),
       ('https://i.imgur.com/dOhLMyA.png', 'Fast Food'),
       ('https://i.imgur.com/Cc5dgNE.png', 'Fast Food'),
       ('https://i.imgur.com/kmciqIS.png', 'Fast Food'),
       ('https://i.imgur.com/1tgqhmK.png', 'Fast Food'),
       ('https://i.imgur.com/xMBVHUb.png', 'Fast Food'),
       ('https://i.imgur.com/whlwvTl.png', 'Fast Food'),
       ('https://i.imgur.com/UJIi3ee.png', 'Fast Food'),
       ('https://i.imgur.com/3Y3vqMc.png', 'Fast Food');

-- Icon group Nội thất
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/VuDNQ3b.png', 'Nội thất'),
       ('https://i.imgur.com/KU0F26I.png', 'Nội thất'),
       ('https://i.imgur.com/aOjDHcy.png', 'Nội thất'),
       ('https://i.imgur.com/ZqQRVFx.png', 'Nội thất'),
       ('https://i.imgur.com/ThdgKe6.png', 'Nội thất'),
       ('https://i.imgur.com/hyQr5t1.png', 'Nội thất'),
       ('https://i.imgur.com/MbeAMwy.png', 'Nội thất'),
       ('https://i.imgur.com/FxEJuBY.png', 'Nội thất'),
       ('https://i.imgur.com/cHFUMGn.png', 'Nội thất'),
       ('https://i.imgur.com/pFnkDqa.png', 'Nội thất'),
       ('https://i.imgur.com/1roxlru.png', 'Nội thất'),
       ('https://i.imgur.com/OFFGrns.png', 'Nội thất'),
       ('https://i.imgur.com/dTbpTle.png', 'Nội thất'),
       ('https://i.imgur.com/IEXN1dw.png', 'Nội thất'),
       ('https://i.imgur.com/kgLKYdB.png', 'Nội thất'),
       ('https://i.imgur.com/oFFbDUC.png', 'Nội thất'),
       ('https://i.imgur.com/9CrOzrT.png', 'Nội thất'),
       ('https://i.imgur.com/azqD6wI.png', 'Nội thất'),
       ('https://i.imgur.com/olP4N6m.png', 'Nội thất'),
       ('https://i.imgur.com/VCirth4.png', 'Nội thất');

-- Icon group Tiện ích
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/3Qu9Vyk.png', 'Tiện ích'),
       ('https://i.imgur.com/X6uNZsD.png', 'Tiện ích'),
       ('https://i.imgur.com/5tADNBJ.png', 'Tiện ích'),
       ('https://i.imgur.com/FXjYkNP.png', 'Tiện ích'),
       ('https://i.imgur.com/IuJ4M9I.png', 'Tiện ích'),
       ('https://i.imgur.com/UimlcbX.png', 'Tiện ích'),
       ('https://i.imgur.com/IAdS966.png', 'Tiện ích'),
       ('https://i.imgur.com/7UaBMJp.png', 'Tiện ích'),
       ('https://i.imgur.com/GGgcR5M.png', 'Tiện ích'),
       ('https://i.imgur.com/serIJZ3.png', 'Tiện ích'),
       ('https://i.imgur.com/r4TW4pS.png', 'Tiện ích'),
       ('https://i.imgur.com/LtVeVO1.png', 'Tiện ích'),
       ('https://i.imgur.com/Yuy8CQK.png', 'Tiện ích'),
       ('https://i.imgur.com/kTeOltA.png', 'Tiện ích'),
       ('https://i.imgur.com/0rKPsZb.png', 'Tiện ích');

-- Icon group Tạp hoá
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/t9BcC9s.png', 'Tạp hoá'),
       ('https://i.imgur.com/PLSrEcA.png', 'Tạp hoá'),
       ('https://i.imgur.com/c95szhh.png', 'Tạp hoá'),
       ('https://i.imgur.com/NS7VODH.png', 'Tạp hoá'),
       ('https://i.imgur.com/V6htS2Y.png', 'Tạp hoá'),
       ('https://i.imgur.com/JQdvLo9.png', 'Tạp hoá'),
       ('https://i.imgur.com/rKY5rZ7.png', 'Tạp hoá'),
       ('https://i.imgur.com/wnWFM6Y.png', 'Tạp hoá'),
       ('https://i.imgur.com/nsBVet5.png', 'Tạp hoá'),
       ('https://i.imgur.com/D1lkSDj.png', 'Tạp hoá'),
       ('https://i.imgur.com/aDywkrq.png', 'Tạp hoá'),
       ('https://i.imgur.com/qOOjfp1.png', 'Tạp hoá'),
       ('https://i.imgur.com/8bneJ89.png', 'Tạp hoá'),
       ('https://i.imgur.com/5ZeCgR1.png', 'Tạp hoá'),
       ('https://i.imgur.com/ESK3F0B.png', 'Tạp hoá'),
       ('https://i.imgur.com/lpt1B1e.png', 'Tạp hoá'),
       ('https://i.imgur.com/Dbarl0m.png', 'Tạp hoá'),
       ('https://i.imgur.com/VtZKIhx.png', 'Tạp hoá'),
       ('https://i.imgur.com/JZx6cFP.png', 'Tạp hoá'),
       ('https://i.imgur.com/DQQCq6Y.png', 'Tạp hoá'),
       ('https://i.imgur.com/zq2JzxC.png', 'Tạp hoá'),
       ('https://i.imgur.com/9K5HGaj.png', 'Tạp hoá'),
       ('https://i.imgur.com/vbWDPVN.png', 'Tạp hoá'),
       ('https://i.imgur.com/H0VD11t.png', 'Tạp hoá'),
       ('https://i.imgur.com/yAH8vfq.png', 'Tạp hoá'),
       ('https://i.imgur.com/r2RVsWF.png', 'Tạp hoá'),
       ('https://i.imgur.com/u6pGw6s.png', 'Tạp hoá'),
       ('https://i.imgur.com/8fgUPaJ.png', 'Tạp hoá'),
       ('https://i.imgur.com/QXlEceP.png', 'Tạp hoá'),
       ('https://i.imgur.com/TwvE0GW.png', 'Tạp hoá');

-- Icon group Dụng cụ cầm tay
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/kN3igTT.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/GoJ0iHU.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/3wUo5AW.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/8w04Hca.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/yk14som.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/bfIvz1j.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/hLZTglK.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/WljuIfg.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/jMCQWJi.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/uLrFegK.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/7m4H9sF.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/yeet9C4.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/u09pHP1.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/oaa389F.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/8GM1Ah5.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/oCStYzi.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/LLA0XLW.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/WCtFMoS.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/5PrMd10.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/7yqhhV4.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/FOBH0Lr.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/U8kBBLR.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/P7c1goq.png', 'Dụng cụ cầm tay'),
       ('https://i.imgur.com/sXoJxgE.png', 'Dụng cụ cầm tay');

-- Icon group Chăm sóc sức khoẻ
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/yjJH4TW.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/bzygCrl.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/UhYUd8G.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/WO660xo.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/GEe56vb.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/63eZjR0.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/KYgc0fH.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/cKSQt2j.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/Y8vULTp.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/CBeZGvy.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/n90K7O9.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/UqwS9M4.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/kMvaVuo.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/mOw1ABS.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/bXMrrWZ.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/2QBt7qO.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/RIs7etb.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/9DhoEJv.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/IoNx3i9.png', 'Chăm sóc sức khoẻ'),
       ('https://i.imgur.com/mLhVhQG.png', 'Chăm sóc sức khoẻ');

-- Icon group Đồ gia dụng
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/eEzL5lp.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/ZGoaKfd.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/FL53lLE.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/E4sxREX.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/z3Lc4YX.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/RQ1Fiss.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/fceVVkc.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/ifQ3zUz.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/E4XNUcd.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/bSNbhgh.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/hHc07YS.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/dJ6L2DZ.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/yOUobQo.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/4dNvlAS.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/JsdMZOV.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/0vZGyDm.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/Kvnisdt.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/gKOTJl6.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/jup9Pm9.png', 'Đồ gia dụng'),
       ('https://i.imgur.com/hdGTklt.png', 'Đồ gia dụng');

-- Icon group Party
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/4nH97Sd.png', 'Party'),
       ('https://i.imgur.com/fRMQxQD.png', 'Party'),
       ('https://i.imgur.com/vtbjcKr.png', 'Party'),
       ('https://i.imgur.com/lVlu5xR.png', 'Party'),
       ('https://i.imgur.com/CxDBmrG.png', 'Party'),
       ('https://i.imgur.com/5SKXk5G.png', 'Party'),
       ('https://i.imgur.com/REuavbx.png', 'Party'),
       ('https://i.imgur.com/NoAo5bE.png', 'Party'),
       ('https://i.imgur.com/PO7w6rZ.png', 'Party'),
       ('https://i.imgur.com/mJxjKIT.png', 'Party'),
       ('https://i.imgur.com/LoW4NUT.png', 'Party'),
       ('https://i.imgur.com/6Htvqz1.png', 'Party'),
       ('https://i.imgur.com/PfM5nWh.png', 'Party'),
       ('https://i.imgur.com/VMDILCK.png', 'Party'),
       ('https://i.imgur.com/vnUu3pp.png', 'Party'),
       ('https://i.imgur.com/xKhaHRe.png', 'Party'),
       ('https://i.imgur.com/Tfoux4z.png', 'Party'),
       ('https://i.imgur.com/zBEAIxm.png', 'Party'),
       ('https://i.imgur.com/RxqUwDD.png', 'Party'),
       ('https://i.imgur.com/J8dgs2s.png', 'Party'),
       ('https://i.imgur.com/CibEGlM.png', 'Party'),
       ('https://i.imgur.com/ONF0IDL.png', 'Party'),
       ('https://i.imgur.com/KKQlsmz.png', 'Party'),
       ('https://i.imgur.com/ZE3l8Vx.png', 'Party');

-- Icon group Thu nhập
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/WLDO9FA.png', 'Thu nhập'),
       ('https://i.imgur.com/QKv7nEl.png', 'Thu nhập'),
       ('https://i.imgur.com/E21g5VG.png', 'Thu nhập'),
       ('https://i.imgur.com/ocnNOCC.png', 'Thu nhập'),
       ('https://i.imgur.com/ItACl1i.png', 'Thu nhập'),
       ('https://i.imgur.com/LDhnE5B.png', 'Thu nhập'),
       ('https://i.imgur.com/Jhi2hVc.png', 'Thu nhập'),
       ('https://i.imgur.com/Px5xjh4.png', 'Thu nhập'),
       ('https://i.imgur.com/9slXp4W.png', 'Thu nhập'),
       ('https://i.imgur.com/ajFrF5y.png', 'Thu nhập'),
       ('https://i.imgur.com/G0GcNM8.png', 'Thu nhập'),
       ('https://i.imgur.com/X0nN3kx.png', 'Thu nhập'),
       ('https://i.imgur.com/u9S8VrV.png', 'Thu nhập'),
       ('https://i.imgur.com/EncsRYN.png', 'Thu nhập'),
       ('https://i.imgur.com/k92YJJS.png', 'Thu nhập'),
       ('https://i.imgur.com/9OFrvMB.png', 'Thu nhập'),
       ('https://i.imgur.com/K0vOovb.png', 'Thu nhập'),
       ('https://i.imgur.com/69EIjPi.png', 'Thu nhập'),
       ('https://i.imgur.com/W2sVdUi.png', 'Thu nhập'),
       ('https://i.imgur.com/5smtk1r.png', 'Thu nhập');

-- Icon group Nhà bếp
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/EsDTWTz.png', 'Nhà bếp'),
       ('https://i.imgur.com/TeIKiXr.png', 'Nhà bếp'),
       ('https://i.imgur.com/YxsdTne.png', 'Nhà bếp'),
       ('https://i.imgur.com/WORkZZr.png', 'Nhà bếp'),
       ('https://i.imgur.com/lEFiAjN.png', 'Nhà bếp'),
       ('https://i.imgur.com/rtuyisZ.png', 'Nhà bếp'),
       ('https://i.imgur.com/jCw80FH.png', 'Nhà bếp'),
       ('https://i.imgur.com/qep7FML.png', 'Nhà bếp'),
       ('https://i.imgur.com/8AtvSzD.png', 'Nhà bếp'),
       ('https://i.imgur.com/8k8CL6B.png', 'Nhà bếp'),
       ('https://i.imgur.com/CPaGasw.png', 'Nhà bếp'),
       ('https://i.imgur.com/OUFRjvz.png', 'Nhà bếp'),
       ('https://i.imgur.com/jGbbUFF.png', 'Nhà bếp'),
       ('https://i.imgur.com/VcZENve.png', 'Nhà bếp'),
       ('https://i.imgur.com/Z2pSlGW.png', 'Nhà bếp'),
       ('https://i.imgur.com/gGcSsa9.png', 'Nhà bếp'),
       ('https://i.imgur.com/BXi5SvJ.png', 'Nhà bếp'),
       ('https://i.imgur.com/KnWzIGS.png', 'Nhà bếp'),
       ('https://i.imgur.com/UPUoAUv.png', 'Nhà bếp'),
       ('https://i.imgur.com/AsWTxfw.png', 'Nhà bếp');

-- Icon group Lifestyle
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/ThrXhtv.png', 'Lifestyle'),
       ('https://i.imgur.com/OpX62R5.png', 'Lifestyle'),
       ('https://i.imgur.com/5UGXuN1.png', 'Lifestyle'),
       ('https://i.imgur.com/zBO3wrD.png', 'Lifestyle'),
       ('https://i.imgur.com/hjUtgWN.png', 'Lifestyle'),
       ('https://i.imgur.com/xkuuGi1.png', 'Lifestyle'),
       ('https://i.imgur.com/IWKbjm7.png', 'Lifestyle'),
       ('https://i.imgur.com/lEQgpzk.png', 'Lifestyle'),
       ('https://i.imgur.com/IilScrL.png', 'Lifestyle'),
       ('https://i.imgur.com/zGinwL9.png', 'Lifestyle'),
       ('https://i.imgur.com/2zHzu43.png', 'Lifestyle'),
       ('https://i.imgur.com/ZapT66u.png', 'Lifestyle'),
       ('https://i.imgur.com/thoczOR.png', 'Lifestyle'),
       ('https://i.imgur.com/VxB1CRw.png', 'Lifestyle'),
       ('https://i.imgur.com/zFpFZb0.png', 'Lifestyle'),
       ('https://i.imgur.com/lF42HjJ.png', 'Lifestyle'),
       ('https://i.imgur.com/nBrXmmr.png', 'Lifestyle'),
       ('https://i.imgur.com/jmyEraQ.png', 'Lifestyle'),
       ('https://i.imgur.com/6mTlRr9.png', 'Lifestyle'),
       ('https://i.imgur.com/oTTUBCr.png', 'Lifestyle'),
       ('https://i.imgur.com/1JLij7F.png', 'Lifestyle');

-- Icon group Luxury Female
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/zYsbOBc.png', 'Luxury Female'),
       ('https://i.imgur.com/caKUqWE.png', 'Luxury Female'),
       ('https://i.imgur.com/FowftSF.png', 'Luxury Female'),
       ('https://i.imgur.com/tubihDd.png', 'Luxury Female'),
       ('https://i.imgur.com/ZzWq63U.png', 'Luxury Female'),
       ('https://i.imgur.com/xLrzQ3r.png', 'Luxury Female'),
       ('https://i.imgur.com/RJ9LTPf.png', 'Luxury Female'),
       ('https://i.imgur.com/e8eO8iS.png', 'Luxury Female'),
       ('https://i.imgur.com/BCZGjIx.png', 'Luxury Female'),
       ('https://i.imgur.com/vf0jx5X.png', 'Luxury Female');

-- Icon group Luxury Fashion
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/Yb0YDHT.png', 'Luxury Fashion'),
       ('https://i.imgur.com/FfWL28U.png', 'Luxury Fashion'),
       ('https://i.imgur.com/Og9nlQn.png', 'Luxury Fashion'),
       ('https://i.imgur.com/xCRUNxb.png', 'Luxury Fashion'),
       ('https://i.imgur.com/uTp3CQE.png', 'Luxury Fashion'),
       ('https://i.imgur.com/XG0Q0Ja.png', 'Luxury Fashion'),
       ('https://i.imgur.com/RZAmuq7.png', 'Luxury Fashion'),
       ('https://i.imgur.com/HBR6aUW.png', 'Luxury Fashion'),
       ('https://i.imgur.com/ulPJ10q.png', 'Luxury Fashion'),
       ('https://i.imgur.com/DzuE7hz.png', 'Luxury Fashion'),
       ('https://i.imgur.com/Dt8kWwq.png', 'Luxury Fashion'),
       ('https://i.imgur.com/MzeGh2R.png', 'Luxury Fashion'),
       ('https://i.imgur.com/eDNVPtd.png', 'Luxury Fashion'),
       ('https://i.imgur.com/gmrvCpN.png', 'Luxury Fashion'),
       ('https://i.imgur.com/t2DmDJd.png', 'Luxury Fashion'),
       ('https://i.imgur.com/lkBtkB9.png', 'Luxury Fashion'),
       ('https://i.imgur.com/xOXIVtk.png', 'Luxury Fashion'),
       ('https://i.imgur.com/sarSe8D.png', 'Luxury Fashion'),
       ('https://i.imgur.com/AxFf1hv.png', 'Luxury Fashion'),
       ('https://i.imgur.com/BpTul2s.png', 'Luxury Fashion');

-- Icon group Man Care
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/wl6z8Qn.png', 'Man Care'),
       ('https://i.imgur.com/WTiXJPi.png', 'Man Care'),
       ('https://i.imgur.com/UEagoY6.png', 'Man Care'),
       ('https://i.imgur.com/W3YnGSC.png', 'Man Care'),
       ('https://i.imgur.com/oyCehSb.png', 'Man Care'),
       ('https://i.imgur.com/TFpuUyT.png', 'Man Care'),
       ('https://i.imgur.com/5bYyGyF.png', 'Man Care'),
       ('https://i.imgur.com/zCInqnW.png', 'Man Care'),
       ('https://i.imgur.com/Tpej0lU.png', 'Man Care'),
       ('https://i.imgur.com/glL7C79.png', 'Man Care'),
       ('https://i.imgur.com/DwINj2a.png', 'Man Care'),
       ('https://i.imgur.com/BgqbAGd.png', 'Man Care'),
       ('https://i.imgur.com/vChJY6p.png', 'Man Care'),
       ('https://i.imgur.com/Wu5iLcz.png', 'Man Care'),
       ('https://i.imgur.com/D3vqCjf.png', 'Man Care'),
       ('https://i.imgur.com/DzQGsik.png', 'Man Care'),
       ('https://i.imgur.com/cfFzAhq.png', 'Man Care'),
       ('https://i.imgur.com/WInJroh.png', 'Man Care'),
       ('https://i.imgur.com/ROE1Hts.png', 'Man Care');

-- Icon group Vật nuôi
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/syruR00.png', 'Vật nuôi'),
       ('https://i.imgur.com/clNjWZq.png', 'Vật nuôi'),
       ('https://i.imgur.com/ASbSKOD.png', 'Vật nuôi'),
       ('https://i.imgur.com/2ntrfEB.png', 'Vật nuôi'),
       ('https://i.imgur.com/s0rAPUy.png', 'Vật nuôi'),
       ('https://i.imgur.com/QrEjtes.png', 'Vật nuôi'),
       ('https://i.imgur.com/Gq8tjwP.png', 'Vật nuôi'),
       ('https://i.imgur.com/Uak9QPH.png', 'Vật nuôi'),
       ('https://i.imgur.com/6bIsZfh.png', 'Vật nuôi'),
       ('https://i.imgur.com/sgoj9Au.png', 'Vật nuôi'),
       ('https://i.imgur.com/LB3mHMs.png', 'Vật nuôi'),
       ('https://i.imgur.com/fakACmz.png', 'Vật nuôi'),
       ('https://i.imgur.com/TSdZvVS.png', 'Vật nuôi'),
       ('https://i.imgur.com/wfOYGdh.png', 'Vật nuôi'),
       ('https://i.imgur.com/GMqct2I.png', 'Vật nuôi'),
       ('https://i.imgur.com/wuFKkcL.png', 'Vật nuôi'),
       ('https://i.imgur.com/jpastnQ.png', 'Vật nuôi'),
       ('https://i.imgur.com/t4eKJ1d.png', 'Vật nuôi'),
       ('https://i.imgur.com/ydprC93.png', 'Vật nuôi'),
       ('https://i.imgur.com/JvsF5cM.png', 'Vật nuôi');

-- Icon group Nhiếp ảnh
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/EWkvOxa.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/a3BWD5Y.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/VzcbwRP.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/I2DE5vz.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/gy7uzh0.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/75QucJx.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/mgkUOUO.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/H9o0RgR.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/2fgvqjL.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/e4L6ofH.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/T8HbxmO.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/gP5EZCH.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/4yac6KK.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/EYd6Fwf.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/gtqV7Hs.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/o80n7Ky.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/kPwSDq2.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/EUSAeo7.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/w3qF69E.png', 'Nhiếp ảnh'),
       ('https://i.imgur.com/SuGXFeM.png', 'Nhiếp ảnh');

-- Icon group Sửa chửa
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/AOYTOXC.png', 'Sửa chửa'),
       ('https://i.imgur.com/Tj11Aeq.png', 'Sửa chửa'),
       ('https://i.imgur.com/8h1oKNF.png', 'Sửa chửa'),
       ('https://i.imgur.com/9FHAmVT.png', 'Sửa chửa'),
       ('https://i.imgur.com/3T1iqPV.png', 'Sửa chửa'),
       ('https://i.imgur.com/Db1ZTTw.png', 'Sửa chửa'),
       ('https://i.imgur.com/pjOjPOW.png', 'Sửa chửa'),
       ('https://i.imgur.com/N6zIpf8.png', 'Sửa chửa'),
       ('https://i.imgur.com/9Ru4eFq.png', 'Sửa chửa'),
       ('https://i.imgur.com/kSFf6K6.png', 'Sửa chửa'),
       ('https://i.imgur.com/sTXei2H.png', 'Sửa chửa'),
       ('https://i.imgur.com/tQ13AES.png', 'Sửa chửa'),
       ('https://i.imgur.com/dRohATd.png', 'Sửa chửa'),
       ('https://i.imgur.com/HieSXGp.png', 'Sửa chửa'),
       ('https://i.imgur.com/tvNMjRo.png', 'Sửa chửa'),
       ('https://i.imgur.com/i4zlRvg.png', 'Sửa chửa'),
       ('https://i.imgur.com/SbMS0MP.png', 'Sửa chửa'),
       ('https://i.imgur.com/WKZQ9A5.png', 'Sửa chửa'),
       ('https://i.imgur.com/UEkt2WJ.png', 'Sửa chửa'),
       ('https://i.imgur.com/a66Ktbb.png', 'Sửa chửa');

-- Icon group Royal
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/ZBBbY3y.png', 'Royal'),
       ('https://i.imgur.com/n2jXOU8.png', 'Royal'),
       ('https://i.imgur.com/zcs5ASD.png', 'Royal'),
       ('https://i.imgur.com/bGlusya.png', 'Royal'),
       ('https://i.imgur.com/tVg02yb.png', 'Royal'),
       ('https://i.imgur.com/WEGtIkg.png', 'Royal'),
       ('https://i.imgur.com/NygmfJc.png', 'Royal'),
       ('https://i.imgur.com/7RgFZue.png', 'Royal'),
       ('https://i.imgur.com/Q8TCaw1.png', 'Royal'),
       ('https://i.imgur.com/qzIN1Ix.png', 'Royal'),
       ('https://i.imgur.com/MLt8pJ9.png', 'Royal'),
       ('https://i.imgur.com/4Dz6AQb.png', 'Royal'),
       ('https://i.imgur.com/UWYdsIF.png', 'Royal'),
       ('https://i.imgur.com/XQolAfz.png', 'Royal'),
       ('https://i.imgur.com/ajkoJ70.png', 'Royal'),
       ('https://i.imgur.com/ISiRlf7.png', 'Royal'),
       ('https://i.imgur.com/YLHK8y2.png', 'Royal'),
       ('https://i.imgur.com/sSjSMAX.png', 'Royal'),
       ('https://i.imgur.com/VIluiyR.png', 'Royal'),
       ('https://i.imgur.com/nTh1czH.png', 'Royal'),
       ('https://i.imgur.com/Ms4WiDU.png', 'Royal'),
       ('https://i.imgur.com/UQuy8OP.png', 'Royal'),
       ('https://i.imgur.com/DFLMk0P.png', 'Royal'),
       ('https://i.imgur.com/rd5g9aO.png', 'Royal'),
       ('https://i.imgur.com/GMC9NFF.png', 'Royal');

-- Icon group Dịch vụ
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/dA3INDn.png', 'Dịch vụ'),
       ('https://i.imgur.com/1dKKqOp.png', 'Dịch vụ'),
       ('https://i.imgur.com/Tge14xC.png', 'Dịch vụ'),
       ('https://i.imgur.com/cVZZClq.png', 'Dịch vụ'),
       ('https://i.imgur.com/RrXafsV.png', 'Dịch vụ'),
       ('https://i.imgur.com/deOTBMU.png', 'Dịch vụ'),
       ('https://i.imgur.com/7kVAFaQ.png', 'Dịch vụ'),
       ('https://i.imgur.com/GEIryiS.png', 'Dịch vụ'),
       ('https://i.imgur.com/X0QFZoP.png', 'Dịch vụ'),
       ('https://i.imgur.com/lFJ8m9e.png', 'Dịch vụ'),
       ('https://i.imgur.com/frFgEQx.png', 'Dịch vụ'),
       ('https://i.imgur.com/pznnaL2.png', 'Dịch vụ'),
       ('https://i.imgur.com/MyGSOI4.png', 'Dịch vụ'),
       ('https://i.imgur.com/0Kv1xVY.png', 'Dịch vụ'),
       ('https://i.imgur.com/TMnnt3f.png', 'Dịch vụ');

-- Icon group Thể thao
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/p45ouqO.png', 'Thể thao'),
       ('https://i.imgur.com/Pl9xZQa.png', 'Thể thao'),
       ('https://i.imgur.com/9ZrJ8nz.png', 'Thể thao'),
       ('https://i.imgur.com/PMFNNrZ.png', 'Thể thao'),
       ('https://i.imgur.com/DZuzzWz.png', 'Thể thao'),
       ('https://i.imgur.com/Padig5D.png', 'Thể thao'),
       ('https://i.imgur.com/vPVKciC.png', 'Thể thao'),
       ('https://i.imgur.com/1lg3xDW.png', 'Thể thao'),
       ('https://i.imgur.com/9bliUvG.png', 'Thể thao'),
       ('https://i.imgur.com/OAiE9Y3.png', 'Thể thao'),
       ('https://i.imgur.com/I8PqM5F.png', 'Thể thao'),
       ('https://i.imgur.com/NwW3xkT.png', 'Thể thao'),
       ('https://i.imgur.com/2RnalMO.png', 'Thể thao'),
       ('https://i.imgur.com/EZSHyDs.png', 'Thể thao'),
       ('https://i.imgur.com/Gcw3aqA.png', 'Thể thao'),
       ('https://i.imgur.com/fNEf0Wb.png', 'Thể thao'),
       ('https://i.imgur.com/IPZXJ0O.png', 'Thể thao'),
       ('https://i.imgur.com/whBSAli.png', 'Thể thao'),
       ('https://i.imgur.com/CNLfpxU.png', 'Thể thao'),
       ('https://i.imgur.com/KoM5zMp.png', 'Thể thao'),
       ('https://i.imgur.com/RlOdoZr.png', 'Thể thao'),
       ('https://i.imgur.com/AVfqG8u.png', 'Thể thao'),
       ('https://i.imgur.com/SlpEGDO.png', 'Thể thao'),
       ('https://i.imgur.com/xYcOu9l.png', 'Thể thao');

-- Icon group Stayhome
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/ESHhPhJ.png', 'Stayhome'),
       ('https://i.imgur.com/3ybjl5q.png', 'Stayhome'),
       ('https://i.imgur.com/oegzarf.png', 'Stayhome'),
       ('https://i.imgur.com/sNicxS9.png', 'Stayhome'),
       ('https://i.imgur.com/9tzly3h.png', 'Stayhome'),
       ('https://i.imgur.com/BFzTtEO.png', 'Stayhome'),
       ('https://i.imgur.com/zmcQZv0.png', 'Stayhome'),
       ('https://i.imgur.com/IfZwWiw.png', 'Stayhome'),
       ('https://i.imgur.com/AqJARzV.png', 'Stayhome'),
       ('https://i.imgur.com/dVR2yvJ.png', 'Stayhome'),
       ('https://i.imgur.com/5sLOqbE.png', 'Stayhome'),
       ('https://i.imgur.com/dLsCtnX.png', 'Stayhome'),
       ('https://i.imgur.com/gYRkBxJ.png', 'Stayhome'),
       ('https://i.imgur.com/k2jDdzV.png', 'Stayhome'),
       ('https://i.imgur.com/x8ZjFOs.png', 'Stayhome'),
       ('https://i.imgur.com/sWWPhcD.png', 'Stayhome'),
       ('https://i.imgur.com/tNu3lP6.png', 'Stayhome'),
       ('https://i.imgur.com/Gk4Jk1j.png', 'Stayhome'),
       ('https://i.imgur.com/JFt5aNp.png', 'Stayhome'),
       ('https://i.imgur.com/fjJbYdM.png', 'Stayhome');

-- Icon group Thailand
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/O0CBv64.png', 'Thailand'),
       ('https://i.imgur.com/iQNkGCD.png', 'Thailand'),
       ('https://i.imgur.com/nfFcnjm.png', 'Thailand'),
       ('https://i.imgur.com/X8wq0NF.png', 'Thailand'),
       ('https://i.imgur.com/0R0kfQE.png', 'Thailand'),
       ('https://i.imgur.com/1OqNXjT.png', 'Thailand'),
       ('https://i.imgur.com/oeAkBsK.png', 'Thailand'),
       ('https://i.imgur.com/484NrKB.png', 'Thailand'),
       ('https://i.imgur.com/qrIwKxJ.png', 'Thailand'),
       ('https://i.imgur.com/yuW4thV.png', 'Thailand'),
       ('https://i.imgur.com/ZpePCOa.png', 'Thailand'),
       ('https://i.imgur.com/ZMGJWWB.png', 'Thailand'),
       ('https://i.imgur.com/2DdrDkR.png', 'Thailand'),
       ('https://i.imgur.com/sbltAOx.png', 'Thailand'),
       ('https://i.imgur.com/PTz1d5U.png', 'Thailand'),
       ('https://i.imgur.com/ih6GzUe.png', 'Thailand'),
       ('https://i.imgur.com/Zsjv1r8.png', 'Thailand'),
       ('https://i.imgur.com/YPjAhki.png', 'Thailand'),
       ('https://i.imgur.com/MkPbdW0.png', 'Thailand'),
       ('https://i.imgur.com/hNIeuxK.png', 'Thailand');

-- Icon group Di chuyển
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/Gddp7eF.png', 'Di chuyển'),
       ('https://i.imgur.com/iIbiqph.png', 'Di chuyển'),
       ('https://i.imgur.com/ATNjQXw.png', 'Di chuyển'),
       ('https://i.imgur.com/l6RVaDv.png', 'Di chuyển'),
       ('https://i.imgur.com/mLsMnTJ.png', 'Di chuyển'),
       ('https://i.imgur.com/NrZXeHE.png', 'Di chuyển'),
       ('https://i.imgur.com/nH41mA0.png', 'Di chuyển'),
       ('https://i.imgur.com/cS32CsX.png', 'Di chuyển'),
       ('https://i.imgur.com/sS9lkUP.png', 'Di chuyển'),
       ('https://i.imgur.com/eJxcNlB.png', 'Di chuyển'),
       ('https://i.imgur.com/mZFNbmt.png', 'Di chuyển'),
       ('https://i.imgur.com/f9tvQTg.png', 'Di chuyển'),
       ('https://i.imgur.com/ACosZpw.png', 'Di chuyển'),
       ('https://i.imgur.com/7AIXmbo.png', 'Di chuyển'),
       ('https://i.imgur.com/TeKQUQk.png', 'Di chuyển'),
       ('https://i.imgur.com/T82e1Vm.png', 'Di chuyển'),
       ('https://i.imgur.com/liwcj2C.png', 'Di chuyển'),
       ('https://i.imgur.com/jELD0Q1.png', 'Di chuyển'),
       ('https://i.imgur.com/wONDV27.png', 'Di chuyển'),
       ('https://i.imgur.com/eSONqRO.png', 'Di chuyển'),
       ('https://i.imgur.com/NYBOBvO.png', 'Di chuyển'),
       ('https://i.imgur.com/Qe3qE0h.png', 'Di chuyển'),
       ('https://i.imgur.com/9rhZc7s.png', 'Di chuyển'),
       ('https://i.imgur.com/xrnO2aa.png', 'Di chuyển'),
       ('https://i.imgur.com/CvjfqTD.png', 'Di chuyển'),
       ('https://i.imgur.com/YGDeZEt.png', 'Di chuyển'),
       ('https://i.imgur.com/rhA0r3P.png', 'Di chuyển'),
       ('https://i.imgur.com/rkTUgeb.png', 'Di chuyển'),
       ('https://i.imgur.com/5LOKjpH.png', 'Di chuyển'),
       ('https://i.imgur.com/t2qDk2a.png', 'Di chuyển');

-- Icon group Du lịch
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/OMpCyXK.png', 'Du lịch'),
       ('https://i.imgur.com/cAKkJS3.png', 'Du lịch'),
       ('https://i.imgur.com/Ix2un0l.png', 'Du lịch'),
       ('https://i.imgur.com/pYHYdoB.png', 'Du lịch'),
       ('https://i.imgur.com/UB7SRZy.png', 'Du lịch'),
       ('https://i.imgur.com/8zzGew2.png', 'Du lịch'),
       ('https://i.imgur.com/KUzsr7V.png', 'Du lịch'),
       ('https://i.imgur.com/NCPuygq.png', 'Du lịch'),
       ('https://i.imgur.com/zYeMU9W.png', 'Du lịch'),
       ('https://i.imgur.com/UoBg0yT.png', 'Du lịch'),
       ('https://i.imgur.com/iJDJwuG.png', 'Du lịch'),
       ('https://i.imgur.com/8dmKoz9.png', 'Du lịch'),
       ('https://i.imgur.com/swiZJBG.png', 'Du lịch'),
       ('https://i.imgur.com/nvMFiwk.png', 'Du lịch'),
       ('https://i.imgur.com/pZP5ymN.png', 'Du lịch'),
       ('https://i.imgur.com/dt4rIun.png', 'Du lịch');

-- Icon group Wedding
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/txrBtEp.png', 'Wedding'),
       ('https://i.imgur.com/VIGdS64.png', 'Wedding'),
       ('https://i.imgur.com/8mWojg3.png', 'Wedding'),
       ('https://i.imgur.com/gtrKR2y.png', 'Wedding'),
       ('https://i.imgur.com/lXxZWij.png', 'Wedding'),
       ('https://i.imgur.com/YmRy92o.png', 'Wedding'),
       ('https://i.imgur.com/gkaBPct.png', 'Wedding'),
       ('https://i.imgur.com/zRNM3lx.png', 'Wedding'),
       ('https://i.imgur.com/NfmyMLZ.png', 'Wedding'),
       ('https://i.imgur.com/oLwq3Rl.png', 'Wedding'),
       ('https://i.imgur.com/vYlCGP9.png', 'Wedding'),
       ('https://i.imgur.com/R2WuMmG.png', 'Wedding'),
       ('https://i.imgur.com/3f4yzw3.png', 'Wedding'),
       ('https://i.imgur.com/zNkdaRK.png', 'Wedding'),
       ('https://i.imgur.com/3xaseuD.png', 'Wedding');

-- Icon group Woman care
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/phNRpW6.png', 'Woman care'),
       ('https://i.imgur.com/Kdnrg2E.png', 'Woman care'),
       ('https://i.imgur.com/bUR1Fte.png', 'Woman care'),
       ('https://i.imgur.com/bAlZAon.png', 'Woman care'),
       ('https://i.imgur.com/rrqqC4E.png', 'Woman care'),
       ('https://i.imgur.com/vsZXhqV.png', 'Woman care'),
       ('https://i.imgur.com/rAK90wu.png', 'Woman care'),
       ('https://i.imgur.com/oh7lurr.png', 'Woman care'),
       ('https://i.imgur.com/49m3JnZ.png', 'Woman care'),
       ('https://i.imgur.com/6zmRbyT.png', 'Woman care'),
       ('https://i.imgur.com/qVwezFx.png', 'Woman care'),
       ('https://i.imgur.com/N0D5scp.png', 'Woman care'),
       ('https://i.imgur.com/es2RXFC.png', 'Woman care'),
       ('https://i.imgur.com/uwyg6p0.png', 'Woman care'),
       ('https://i.imgur.com/JOzotMX.png', 'Woman care'),
       ('https://i.imgur.com/hfdcT16.png', 'Woman care'),
       ('https://i.imgur.com/mwMnwrK.png', 'Woman care'),
       ('https://i.imgur.com/qDFMKxU.png', 'Woman care'),
       ('https://i.imgur.com/loGKkhb.png', 'Woman care'),
       ('https://i.imgur.com/M0PziDK.png', 'Woman care'),
       ('https://i.imgur.com/UImJZsc.png', 'Woman care'),
       ('https://i.imgur.com/wgTMUGg.png', 'Woman care'),
       ('https://i.imgur.com/VViHLNt.png', 'Woman care'),
       ('https://i.imgur.com/2LwXEcA.png', 'Woman care'),
       ('https://i.imgur.com/qsDRzKd.png', 'Woman care'),
       ('https://i.imgur.com/hoDU1r2.png', 'Woman care'),
       ('https://i.imgur.com/7weUtkp.png', 'Woman care'),
       ('https://i.imgur.com/f5d3ppg.png', 'Woman care'),
       ('https://i.imgur.com/25TuG49.png', 'Woman care'),
       ('https://i.imgur.com/A9zs0y0.png', 'Woman care');

-- Icon group Khác
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/6UAIbrO.png', 'Khác'),
       ('https://i.imgur.com/wjstZSV.png', 'Khác'),
       ('https://i.imgur.com/paqPBLF.png', 'Khác'),
       ('https://i.imgur.com/QV5YOdJ.png', 'Khác'),
       ('https://i.imgur.com/GrxIwbT.png', 'Khác'),
       ('https://i.imgur.com/qT2aPeK.png', 'Khác'),
       ('https://i.imgur.com/MA12AcG.png', 'Khác'),
       ('https://i.imgur.com/oaViIUw.png', 'Khác'),
       ('https://i.imgur.com/ncpb5GF.png', 'Khác'),
       ('https://i.imgur.com/PIZZl2p.png', 'Khác'),
       ('https://i.imgur.com/Gh4ZZTS.png', 'Khác'),
       ('https://i.imgur.com/5YZT8v6.png', 'Khác'),
       ('https://i.imgur.com/MyuO3Lu.png', 'Khác'),
       ('https://i.imgur.com/GyipVQL.png', 'Khác'),
       ('https://i.imgur.com/h78RSCi.png', 'Khác'),
       ('https://i.imgur.com/4tN3KSl.png', 'Khác'),
       ('https://i.imgur.com/0VTlT1v.png', 'Khác'),
       ('https://i.imgur.com/qEdmLAK.png', 'Khác'),
       ('https://i.imgur.com/eDys2Qt.png', 'Khác'),
       ('https://i.imgur.com/ARCzTO1.png', 'Khác'),
       ('https://i.imgur.com/LHtc1GR.png', 'Khác'),
       ('https://i.imgur.com/KnEm5Kl.png', 'Khác'),
       ('https://i.imgur.com/zmOHj3G.png', 'Khác'),
       ('https://i.imgur.com/Nwd80r0.png', 'Khác'),
       ('https://i.imgur.com/ijJi0gp.png', 'Khác'),
       ('https://i.imgur.com/NcdR860.png', 'Khác'),
       ('https://i.imgur.com/ISO0pys.png', 'Khác'),
       ('https://i.imgur.com/wIECb76.png', 'Khác'),
       ('https://i.imgur.com/mfUJ5gD.png', 'Khác'),
       ('https://i.imgur.com/U1UusSr.png', 'Khác');
