-- Icon group Co Ban
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/eXbvWGr.png', 'Cơ bản')
     , ('https://i.imgur.com/ULVNR2Z.png', 'Cơ bản')
     , ('https://i.imgur.com/J17uqGk.png', 'Cơ bản')
     , ('https://i.imgur.com/NSrNfeY.png', 'Cơ bản')
     , ('https://i.imgur.com/POh6KnC.png', 'Cơ bản')
     , ('https://i.imgur.com/Wf4jA7G.png', 'Cơ bản')
     , ('https://i.imgur.com/4Iphax2.png', 'Cơ bản')
     , ('https://i.imgur.com/Aq8JECE.png', 'Cơ bản')
     , ('https://i.imgur.com/fLIoa3Q.png', 'Cơ bản')
     , ('https://i.imgur.com/NUSx4Yt.png', 'Cơ bản')
     , ('https://i.imgur.com/5vJGhQ3.png', 'Cơ bản')
     , ('https://i.imgur.com/JCvQv0j.png', 'Cơ bản')
     , ('https://i.imgur.com/ZbrKTcK.png', 'Cơ bản')
     , ('https://i.imgur.com/jTGFORK.png', 'Cơ bản')
     , ('https://i.imgur.com/3DgpwJX.png', 'Cơ bản')
     , ('https://i.imgur.com/JWgzRAc.png', 'Cơ bản')
     , ('https://i.imgur.com/xwTv8Qx.png', 'Cơ bản')
     , ('https://i.imgur.com/VkhcSlW.png', 'Cơ bản')
     , ('https://i.imgur.com/gKeVZhC.png', 'Cơ bản')
     , ('https://i.imgur.com/5Evri5E.png', 'Cơ bản')
     , ('https://i.imgur.com/9PP5L78.png', 'Cơ bản')
     , ('https://i.imgur.com/1WBggv3.png', 'Cơ bản')
     , ('https://i.imgur.com/KDPIkPl.png', 'Cơ bản')
     , ('https://i.imgur.com/FtmhxhM.png', 'Cơ bản')
     , ('https://i.imgur.com/cAS7vVt.png', 'Cơ bản')
     , ('https://i.imgur.com/L0VLoUR.png', 'Cơ bản')
     , ('https://i.imgur.com/WRLJons.png', 'Cơ bản')
     , ('https://i.imgur.com/XyNMh7l.png', 'Cơ bản')
     , ('https://i.imgur.com/dVjG92V.png', 'Cơ bản')
     , ('https://i.imgur.com/BnQxJvy.png', 'Cơ bản')
     , ('https://i.imgur.com/ucHbcW9.png', 'Cơ bản')
     , ('https://i.imgur.com/OskBJYb.png', 'Cơ bản')
     , ('https://i.imgur.com/l7siP48.png', 'Cơ bản')
     , ('https://i.imgur.com/JJWUVbb.png', 'Cơ bản')
     , ('https://i.imgur.com/tW5hP9A.png', 'Cơ bản')
     , ('https://i.imgur.com/o3d6S0a.png', 'Cơ bản')
     , ('https://i.imgur.com/P3T1OwF.png', 'Cơ bản')
     , ('https://i.imgur.com/OUKazxc.png', 'Cơ bản')
     , ('https://i.imgur.com/6SQVBzR.png', 'Cơ bản')
     , ('https://i.imgur.com/rbQqQ6u.png', 'Cơ bản')
     , ('https://i.imgur.com/brIkeR4.png', 'Cơ bản')
     , ('https://i.imgur.com/LnuV0TL.png', 'Cơ bản')
     , ('https://i.imgur.com/IgrzgoI.png', 'Cơ bản')
     , ('https://i.imgur.com/AjhjzKn.png', 'Cơ bản')
     , ('https://i.imgur.com/EAgtTF2.png', 'Cơ bản')
     , ('https://i.imgur.com/KI9SPsO.png', 'Cơ bản')
     , ('https://i.imgur.com/09japkY.png', 'Cơ bản')
     , ('https://i.imgur.com/zOZjUOj.png', 'Cơ bản')
     , ('https://i.imgur.com/57fqaCj.png', 'Cơ bản')
     , ('https://i.imgur.com/5w5cFMs.png', 'Cơ bản')
     , ('https://i.imgur.com/U756gpf.png', 'Cơ bản')
     , ('https://i.imgur.com/ITR24vf.png', 'Cơ bản')
     , ('https://i.imgur.com/eULQ5di.png', 'Cơ bản')
     , ('https://i.imgur.com/DxYWxh4.png', 'Cơ bản')
     , ('https://i.imgur.com/pBkggYH.png', 'Cơ bản')
     , ('https://i.imgur.com/IHFU8Ma.png', 'Cơ bản')
     , ('https://i.imgur.com/nW6DxsZ.png', 'Cơ bản')
     , ('https://i.imgur.com/CCw5zyp.png', 'Cơ bản')
     , ('https://i.imgur.com/vt25RJJ.png', 'Cơ bản')
     , ('https://i.imgur.com/hiwsNzj.png', 'Cơ bản')
     , ('https://i.imgur.com/cGCrUVQ.png', 'Cơ bản')
     , ('https://i.imgur.com/wZCjxGa.png', 'Cơ bản')
     , ('https://i.imgur.com/Xyex6Nt.png', 'Cơ bản')
     , ('https://i.imgur.com/DbGXERG.png', 'Cơ bản')
     , ('https://i.imgur.com/x53YDdI.png', 'Cơ bản')
     , ('https://i.imgur.com/Ao2XnV0.png', 'Cơ bản')
     , ('https://i.imgur.com/ypT1zfK.png', 'Cơ bản')
     , ('https://i.imgur.com/hXuVdua.png', 'Cơ bản')
     , ('https://i.imgur.com/FlNl8LQ.png', 'Cơ bản')
     , ('https://i.imgur.com/7UfVqt1.png', 'Cơ bản')
     , ('https://i.imgur.com/dmrAgSA.png', 'Cơ bản')
     , ('https://i.imgur.com/QAqH8cm.png', 'Cơ bản')
     , ('https://i.imgur.com/61UlCaE.png', 'Cơ bản')
     , ('https://i.imgur.com/5l9XRHl.png', 'Cơ bản')
     , ('https://i.imgur.com/KpyVKDM.png', 'Cơ bản')
     , ('https://i.imgur.com/0roya2d.png', 'Cơ bản')
     , ('https://i.imgur.com/JO3USI6.png', 'Cơ bản')
     , ('https://i.imgur.com/wDAnRjI.png', 'Cơ bản')
     , ('https://i.imgur.com/V3HL3Nz.png', 'Cơ bản')
     , ('https://i.imgur.com/u8VRgeo.png', 'Cơ bản')
     , ('https://i.imgur.com/GmwBWLc.png', 'Cơ bản')
     , ('https://i.imgur.com/SJ1emLe.png', 'Cơ bản')
     , ('https://i.imgur.com/MQSGP2c.png', 'Cơ bản')
     , ('https://i.imgur.com/cKHABIh.png', 'Cơ bản')
     , ('https://i.imgur.com/M6gWaOe.png', 'Cơ bản')
     , ('https://i.imgur.com/aHXoH4K.png', 'Cơ bản')
     , ('https://i.imgur.com/QpRgwRi.png', 'Cơ bản')
     , ('https://i.imgur.com/Vd44oZX.png', 'Cơ bản')
     , ('https://i.imgur.com/jrLMJVi.png', 'Cơ bản')
     , ('https://i.imgur.com/oZzjRP9.png', 'Cơ bản')
     , ('https://i.imgur.com/l8Yml3O.png', 'Cơ bản')
     , ('https://i.imgur.com/Yo73D5G.png', 'Cơ bản')
     , ('https://i.imgur.com/nw8Knhx.png', 'Cơ bản')
     , ('https://i.imgur.com/zRxRYsb.png', 'Cơ bản')
     , ('https://i.imgur.com/YEJvaI7.png', 'Cơ bản')
     , ('https://i.imgur.com/xMHbnr8.png', 'Cơ bản')
     , ('https://i.imgur.com/ZvleH20.png', 'Cơ bản')
     , ('https://i.imgur.com/KcIv8yZ.png', 'Cơ bản')
     , ('https://i.imgur.com/XxxQu45.png', 'Cơ bản')
     , ('https://i.imgur.com/dUof97K.png', 'Cơ bản')
     , ('https://i.imgur.com/Vx6fW8T.png', 'Cơ bản')
     , ('https://i.imgur.com/KPuUYUQ.png', 'Cơ bản')
     , ('https://i.imgur.com/4STBQHc.png', 'Cơ bản')
     , ('https://i.imgur.com/J5dJje0.png', 'Cơ bản')
     , ('https://i.imgur.com/LjtSabP.png', 'Cơ bản')
     , ('https://i.imgur.com/0L64bgK.png', 'Cơ bản')
     , ('https://i.imgur.com/XzAfk00.png', 'Cơ bản')
     , ('https://i.imgur.com/aHDXKIl.png', 'Cơ bản')
     , ('https://i.imgur.com/6B6bt1T.png', 'Cơ bản')
     , ('https://i.imgur.com/kyXDAYJ.png', 'Cơ bản')
     , ('https://i.imgur.com/a9ALR0O.png', 'Cơ bản')
     , ('https://i.imgur.com/YsF48D6.png', 'Cơ bản')
     , ('https://i.imgur.com/ZNxKndM.png', 'Cơ bản')
     , ('https://i.imgur.com/MtWSJpm.png', 'Cơ bản')
     , ('https://i.imgur.com/t0Vfzim.png', 'Cơ bản')
     , ('https://i.imgur.com/JpQuHvW.png', 'Cơ bản')
     , ('https://i.imgur.com/CI05PMe.png', 'Cơ bản')
     , ('https://i.imgur.com/2fvkd8Y.png', 'Cơ bản')
     , ('https://i.imgur.com/PwDcyib.png', 'Cơ bản')
     , ('https://i.imgur.com/AkOzo6l.png', 'Cơ bản')
     , ('https://i.imgur.com/wpQJRwP.png', 'Cơ bản')
     , ('https://i.imgur.com/zImaOvF.png', 'Cơ bản')
     , ('https://i.imgur.com/yzoXQRs.png', 'Cơ bản')
     , ('https://i.imgur.com/Mcbcg5n.png', 'Cơ bản')
     , ('https://i.imgur.com/DOxa9ya.png', 'Cơ bản')
     , ('https://i.imgur.com/CRHbgth.png', 'Cơ bản')
     , ('https://i.imgur.com/wtKcFnK.png', 'Cơ bản')
     , ('https://i.imgur.com/NM1uur3.png', 'Cơ bản')
     , ('https://i.imgur.com/MuTyQPe.png', 'Cơ bản')
     , ('https://i.imgur.com/NwtGNeH.png', 'Cơ bản')
     , ('https://i.imgur.com/rJjLh2i.png', 'Cơ bản')
     , ('https://i.imgur.com/d2H1WhC.png', 'Cơ bản')
     , ('https://i.imgur.com/Ks7ahPa.png', 'Cơ bản')
     , ('https://i.imgur.com/fpXfr6m.png', 'Cơ bản')
     , ('https://i.imgur.com/0XVA6C9.png', 'Cơ bản')
     , ('https://i.imgur.com/S4GLOzn.png', 'Cơ bản')
     , ('https://i.imgur.com/pWgsAbn.png', 'Cơ bản')
     , ('https://i.imgur.com/8OCe03t.png', 'Cơ bản')
     , ('https://i.imgur.com/smU5MJD.png', 'Cơ bản')
     , ('https://i.imgur.com/I6YvO5a.png', 'Cơ bản')
     , ('https://i.imgur.com/AdoRMVL.png', 'Cơ bản');

-- Icon group Ngan hang Viet Nam
insert into icon(icon_url, group_icon)
values ('https://i.imgur.com/5KXTCqA.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/VifLKZb.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/gpSN9GB.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/Ak15KWj.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/uRmLuks.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/1JbnIrK.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/BeGgnhP.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/K6iKJ7U.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/xgBK3gQ.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/kt6rtEX.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/Dhm0A9m.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/4Waxp4Z.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/zqXcix3.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/pNsl71S.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/EfbPyF3.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/Id893VS.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/GmYqqiX.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/0PNsHNt.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/kg2CMp5.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/qrJKTWP.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/17pbzer.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/g2Bfpgv.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/jpohCH5.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/T4ykzBA.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/MztBUHA.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/3gm0wzH.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/BtyDf88.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/FXVw66b.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/MWVT6Iq.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/brkgfoy.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/xLs0pMj.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/rVb40xO.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/uk5Day7.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/q44bYFn.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/A3SklRA.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/6mV6Y4p.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/pdd0t5y.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/8HlpzbM.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/DfAXNEd.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/IHN4vna.png', 'Ngân hàng Việt Nam')
     , ('https://i.imgur.com/bpvikWg.png', 'Ngân hàng Việt Nam');
